### PR TITLE
Enhance beforeInitialView in order to be able to tune main Stage

### PR DESCRIPTION
**Pull request by ouaibsky**
according to some bean information.

My use case is simple:
* Be able to tune the main stage according to some beans value and/or spring profile activated. (before showing the main stage)

### CODE REVIEW

**Comment by ouaibsky** [comment]
I changed nothing in pom, weird that dependency download failed.
works fine behind my company proxy.

**Comment by ouaibsky** [comment]
Trigger

**Comment by ouaibsky** [comment]
retest this please

**Comment by roskenet** [comment]
Yes, don't worry about that...
It's the same as in my company: You have the spring framework milestone versions already in your company's repo.
I'll take a look asap!

**Comment by ouaibsky** [comment]
Ok
I would like to propose a couple of minor enhancement.
How do you want to process:
* Discuss within an issue then doing PR
* propose PR directly ?

Let me know.

**Comment by ouaibsky** [comment]
Hi
Any news ?
* Do u wanna me to push again ?
Cheers
Christophe.

**Comment by ouaibsky** [comment]
Looks good
Any concerns to merge ?
Chris

**Comment by roskenet** [comment]
Hey Chris...
Sorry for waiting the long delay - but had a lot of different stuff to do.
Thanks for your contribution!

**Pull request merged**
